// Contract tests for the per-host plugin manifests generated by
// `build/gen-manifests.mjs`, and for the two root-scan ignore files that
// control what Hermes/ClawHub see when installing from a Git source.
//
// Per this project's test-hygiene rule ("a test that merely re-reads a
// generated file it also generated proves nothing"), the content assertions
// below compare each manifest against an INDEPENDENT source — `package.json`
// and `skills/fezo/SKILL.md`'s frontmatter — never against
// `build/gen-manifests.mjs`'s own constants. Only the freshness test invokes
// the generator, and it writes to a scratch root so no test can dirty the
// committed files it is checking.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const genManifestsPath = join(repoRoot, 'build', 'gen-manifests.mjs');
const skillMdPath = join(repoRoot, 'skills', 'fezo', 'SKILL.md');

interface PackageJson {
  name: string;
  version: string;
  description: string;
  homepage: string;
  license: string;
  repository: { url: string };
}

const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8')) as PackageJson;

/** The relative paths the generator owns, read from the generator itself via
 * `--list` so adding a host lane cannot leave these tests behind. */
const manifestPaths: string[] = execFileSync('node', [genManifestsPath, '--list'], { encoding: 'utf8' })
  .trim()
  .split('\n')
  .filter((line) => line.length > 0);

function readManifest(relPath: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(repoRoot, relPath), 'utf8')) as Record<string, unknown>;
}

/** The skill `description` as it appears in SKILL.md's frontmatter — the
 * independent source every manifest's description must equal. */
function skillDescriptionFromFrontmatter(): string {
  const skillMd = readFileSync(skillMdPath, 'utf8');
  const match = skillMd.match(/^---\n([\s\S]*?)\n---\n/);
  if (match === null) throw new Error('SKILL.md has no --- frontmatter block');
  const line = match[1]!.split('\n').find((l) => l.startsWith('description: '));
  if (line === undefined) throw new Error('SKILL.md frontmatter has no description');
  return line.slice('description: '.length);
}

/** Every `"version"` string anywhere in a manifest, at any nesting depth. A
 * top-level-only check would miss the copies inside `plugins[]`, which is
 * exactly where a marketplace listing's version lives. */
function collectVersions(value: unknown, found: string[] = []): string[] {
  if (Array.isArray(value)) {
    for (const item of value) collectVersions(item, found);
  } else if (value !== null && typeof value === 'object') {
    for (const [key, nested] of Object.entries(value)) {
      if (key === 'version' && typeof nested === 'string') found.push(nested);
      else collectVersions(nested, found);
    }
  }
  return found;
}

describe('per-host plugin manifests', () => {
  it('the generator owns the lanes this project documents', () => {
    expect(manifestPaths).toEqual([
      '.claude-plugin/plugin.json',
      '.claude-plugin/marketplace.json',
      '.codex-plugin/plugin.json',
      '.grok-plugin/plugin.json',
      '.grok-plugin/marketplace.json',
      '.agents/plugins/marketplace.json',
      'gemini-extension.json',
    ]);
  });

  // `git diff` reports nothing for an untracked path, so CI's freshness gate
  // would pass vacuously on a manifest that was generated but never committed.
  // Hosts read these files out of the repository, so untracked means absent.
  it('every manifest is tracked by git', () => {
    for (const relPath of manifestPaths) {
      let tracked = true;
      try {
        execFileSync('git', ['ls-files', '--error-unmatch', '--', relPath], {
          cwd: repoRoot,
          stdio: 'pipe',
        });
      } catch {
        tracked = false;
      }
      expect(tracked, `${relPath} is not tracked by git — 'git add' it`).toBe(true);
    }
  });

  it('every manifest exists, is valid JSON, and ends in a single newline', () => {
    for (const relPath of manifestPaths) {
      const raw = readFileSync(join(repoRoot, relPath), 'utf8');
      expect(() => JSON.parse(raw), relPath).not.toThrow();
      expect(raw.endsWith('}\n'), relPath).toBe(true);
      expect(raw.endsWith('}\n\n'), relPath).toBe(false);
    }
  });

  // The reason these files are generated at all. Seven manifests times one
  // version field each is seven ways to publish a release number that was
  // never cut.
  it('every version string in every manifest equals package.json\'s version', () => {
    // `.agents/plugins/marketplace.json` carries no version on purpose: it
    // resolves the plugin by git URL, so the host takes the version from the
    // clone. Naming it explicitly keeps the guard sharp — a manifest that
    // silently LOSES its version field still fails this test rather than
    // passing vacuously.
    const versionless = new Set(['.agents/plugins/marketplace.json']);
    for (const relPath of manifestPaths) {
      const versions = collectVersions(readManifest(relPath));
      if (versionless.has(relPath)) {
        expect(versions, `${relPath} is expected to declare no version`).toEqual([]);
        continue;
      }
      expect(versions.length, `${relPath} declares no version`).toBeGreaterThan(0);
      for (const version of versions) {
        expect(version, relPath).toBe(pkg.version);
      }
    }
  });

  it('every description equals SKILL.md\'s frontmatter description', () => {
    const expected = skillDescriptionFromFrontmatter();
    // gemini-extension.json describes the PACKAGE (it is an extension manifest,
    // not a skill manifest), so it carries package.json's description instead.
    const packageDescribed = new Set(['gemini-extension.json']);
    for (const relPath of manifestPaths) {
      const manifest = readManifest(relPath);
      const plugins = manifest.plugins;
      const descriptions: string[] = [];
      if (typeof manifest.description === 'string') descriptions.push(manifest.description);
      if (Array.isArray(plugins)) {
        for (const plugin of plugins) {
          const description = (plugin as Record<string, unknown>).description;
          if (typeof description === 'string') descriptions.push(description);
        }
      }
      for (const description of descriptions) {
        // A marketplace wrapper's own description is about the marketplace, not
        // the skill; only skill/plugin-level descriptions are pinned.
        if (description.startsWith('Marketplace ')) continue;
        expect(description, relPath).toBe(packageDescribed.has(relPath) ? pkg.description : expected);
      }
    }
  });

  it('every clone URL drops npm\'s `git+` prefix and every homepage matches package.json', () => {
    const expectedGitUrl = pkg.repository.url.replace(/^git\+/, '');
    expect(expectedGitUrl.startsWith('git+')).toBe(false);
    const raw = manifestPaths.map((relPath) => readFileSync(join(repoRoot, relPath), 'utf8')).join('\n');
    // `git+https://…` is meaningful to npm and is rejected or mangled by plugin
    // hosts, so it must not survive into any manifest.
    expect(raw).not.toContain('git+');
    for (const relPath of manifestPaths) {
      const text = readFileSync(join(repoRoot, relPath), 'utf8');
      if (text.includes('"homepage"')) {
        expect(text, relPath).toContain(pkg.homepage);
      }
    }
  });

  it('are byte-identical to a fresh generation (CI\'s manifest freshness gate)', () => {
    const scratchRoot = mkdtempSync(join(tmpdir(), 'fezo-manifests-'));
    try {
      execFileSync('node', [genManifestsPath, '--out', scratchRoot], { cwd: repoRoot, encoding: 'utf8' });
      for (const relPath of manifestPaths) {
        const fresh = readFileSync(join(scratchRoot, relPath));
        const committed = readFileSync(join(repoRoot, relPath));
        expect(fresh.equals(committed), `${relPath} is stale — run 'pnpm gen-manifests'`).toBe(true);
      }
    } finally {
      rmSync(scratchRoot, { recursive: true, force: true });
    }
  });

  it('generating twice produces identical output (no clock or randomness)', () => {
    const a = mkdtempSync(join(tmpdir(), 'fezo-manifests-a-'));
    const b = mkdtempSync(join(tmpdir(), 'fezo-manifests-b-'));
    try {
      execFileSync('node', [genManifestsPath, '--out', a], { cwd: repoRoot, encoding: 'utf8' });
      execFileSync('node', [genManifestsPath, '--out', b], { cwd: repoRoot, encoding: 'utf8' });
      for (const relPath of manifestPaths) {
        expect(readFileSync(join(a, relPath)).equals(readFileSync(join(b, relPath))), relPath).toBe(true);
      }
    } finally {
      rmSync(a, { recursive: true, force: true });
      rmSync(b, { recursive: true, force: true });
    }
  });

  // Design principle #3 (no static backend roster) applied to packaging. A
  // marketplace listing is the worst place for a provider name: it is public,
  // cached by the host, and updated by nobody when the gateway's catalog
  // changes.
  it('no manifest names a specific backend provider', () => {
    const raw = manifestPaths.map((relPath) => readFileSync(join(repoRoot, relPath), 'utf8')).join('\n').toLowerCase();
    for (const provider of ['exa', 'serper', 'tavily', 'brave', 'apify', 'scrapecreators', 'openai', 'perplexity']) {
      expect(raw, `manifests must not name the backend "${provider}"`).not.toContain(provider);
    }
  });

  it('Gemini settings advertise exactly the two credential env vars fezoctl reads', () => {
    const gemini = readManifest('gemini-extension.json');
    const settings = gemini.settings as { envVar: string; sensitive: boolean }[];
    // Exact equality, not a subset: resolution accepts these two names and no
    // others, so a third entry here would advertise a variable that silently
    // does nothing.
    expect(settings.map((s) => s.envVar)).toEqual(['FEZO_URL', 'FEZO_API_KEY']);
    // The API key must be marked sensitive so the host masks it; the gateway
    // URL is not a secret.
    expect(settings.find((s) => s.envVar === 'FEZO_API_KEY')?.sensitive).toBe(true);
    expect(settings.find((s) => s.envVar === 'FEZO_URL')?.sensitive).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Root-scan ignore files. Hermes and ClawHub scan the WHOLE repository when
// installing from a Git source, so these decide what an installed skill
// contains. Excluding the engine here would produce the same silent failure
// that gitignoring it did: a SKILL.md with no fezoctl behind it.
// ---------------------------------------------------------------------------

describe('root-scan ignore files', () => {
  const ignoreFiles = ['.skillignore', '.clawhubignore'];

  function patterns(relPath: string): string[] {
    return readFileSync(join(repoRoot, relPath), 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith('#'));
  }

  it('both exist and exclude the same paths', () => {
    const [skillignore, clawhubignore] = ignoreFiles.map(patterns) as [string[], string[]];
    expect(skillignore.length).toBeGreaterThan(0);
    expect(clawhubignore).toEqual(skillignore);
  });

  it('neither excludes the skill directory or its engine', () => {
    for (const relPath of ignoreFiles) {
      for (const pattern of patterns(relPath)) {
        // Anything rooted at `skills/` would take the runtime skill — or the
        // committed bundle inside it — out of the installed payload.
        expect(pattern.startsWith('skills/'), `${relPath}: "${pattern}" would exclude the runtime skill`).toBe(false);
        expect(pattern, relPath).not.toBe('skills');
        expect(pattern.includes('fezoctl'), `${relPath}: "${pattern}" would exclude the engine`).toBe(false);
      }
    }
  });

  it('both exclude every host manifest and the dev tooling', () => {
    for (const relPath of ignoreFiles) {
      const declared = patterns(relPath);
      for (const expected of ['src/', 'tests/', 'build/', '.github/', 'node_modules/', 'gemini-extension.json']) {
        expect(declared, relPath).toContain(expected);
      }
      // Each host reads only its own manifest; the others are scan noise.
      for (const dir of ['.claude-plugin/', '.codex-plugin/', '.grok-plugin/', '.agents/']) {
        expect(declared, relPath).toContain(dir);
      }
    }
  });

  it('neither excludes CONFIGURATION.md — SKILL.md sends the user there for setup', () => {
    for (const relPath of ignoreFiles) {
      expect(patterns(relPath), relPath).not.toContain('CONFIGURATION.md');
    }
  });
});
